name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        env:
          spring.datasource.url: ${{ secrets.MYSQL_URL }}
          spring.datasource.username: ${{ secrets.MYSQL_USER_NAME }}
          spring.datasource.password: ${{ secrets.MYSQL_PASSWORD }}
          spring.jwt.secret: ${{ secrets.JWT_SECRET }}
          security.password.iterations: ${{ secrets.PASSWORD_ITERATIONS }}
          security.password.memory: ${{ secrets.PASSWORD_MEMORY }}
          security.password.parallelism: ${{ secrets.PASSWORD_PARALLELISM }}
          image.api-url: ${{ secrets.IMAGE_API_URL }}

        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            PROJECT_DIR="/home/ubuntu/logbuffer"
            cd "$PROJECT_DIR"
            git fetch
            git reset --hard origin/dev
            PID=$(sudo lsof -t -i :8080 || true)
            kill -9 "$PID"
            sleep 5
            ./gradlew build -x test
            nohup java -Dspring.datasource.url=${{ secrets.MYSQL_URL }} \
            -Dspring.datasource.username=${{ secrets.MYSQL_USER_NAME }} \
            -Dspring.datasource.password=${{ secrets.MYSQL_PASSWORD }} \
            -Djwt.secret=${{ secrets.JWT_SECRET }} \
            -Dsecurity.password.iterations=${{ secrets.PASSWORD_ITERATIONS }} \
            -Dsecurity.password.memory=${{ secrets.PASSWORD_MEMORY }} \
            -Dsecurity.password.parallelism=${{ secrets.PASSWORD_PARALLELISM }} \
            -Dimage.api-url=${{ secrets.IMAGE_API_URL }} \
            -jar build/libs/logbuffer-0.0.1-SNAPSHOT.jar > application.log 2>&1 &